### ISSUE TITLE
3.2.2 builds

### ISSUE THREAD

**Issue by echodreamz** [magnxpyr/phalcon.so#1]
Any chance of 3.2.2 builds?

Thanks!

**Comment by stefanchiriac** [comment]
I'll try to update them tonight. Somehow I missed the latest release :expressionless:

**Comment by echodreamz** [comment]
Thank you sir!

**Comment by stefanchiriac** [comment]
All updated
https://github.com/magnxpyr/phalcon.so/releases/tag/phalcon3.2
